/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-04-24 06:43:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contents_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>푸드뷰</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-2.2.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\"#cafe\").mouseenter(function(){\r\n");
      out.write("\t\t$(\"#cafeTitle\").css(\"display\", \"block\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#krFood\").mouseenter(function(){\r\n");
      out.write("\t\t$(\"#krFoodTitle\").css(\"display\", \"block\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#jpFood\").mouseenter(function(){\r\n");
      out.write("\t\t$(\"#jpFoodTitle\").css(\"display\", \"block\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#wsFood\").mouseenter(function(){\r\n");
      out.write("\t\t$(\"#wsFoodTitle\").css(\"display\", \"block\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#chFood\").mouseenter(function(){\r\n");
      out.write("\t\t$(\"#chFoodTitle\").css(\"display\", \"block\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#snack\").mouseenter(function(){\r\n");
      out.write("\t\t$(\"#snackTitle\").css(\"display\", \"block\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#drink\").mouseenter(function(){\r\n");
      out.write("\t\t$(\"#drinkTitle\").css(\"display\", \"block\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#cafe\").mouseleave(function(){\r\n");
      out.write("\t\t$(\"#cafeTitle\").css(\"display\", \"none\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#krFood\").mouseleave(function(){\r\n");
      out.write("\t\t$(\"#krFoodTitle\").css(\"display\", \"none\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#jpFood\").mouseleave(function(){\r\n");
      out.write("\t\t$(\"#jpFoodTitle\").css(\"display\", \"none\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#wsFood\").mouseleave(function(){\r\n");
      out.write("\t\t$(\"#wsFoodTitle\").css(\"display\", \"none\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#chFood\").mouseleave(function(){\r\n");
      out.write("\t\t$(\"#chFoodTitle\").css(\"display\", \"none\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#snack\").mouseleave(function(){\r\n");
      out.write("\t\t$(\"#snackTitle\").css(\"display\", \"none\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#drink\").mouseleave(function(){\r\n");
      out.write("\t\t$(\"#drinkTitle\").css(\"display\", \"none\");\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("table{\r\n");
      out.write("\tclear:both;\r\n");
      out.write("\tmargin:auto;\r\n");
      out.write("}\r\n");
      out.write("#category{\r\n");
      out.write("\tclear:both;\r\n");
      out.write("}\r\n");
      out.write("#aside{ \r\n");
      out.write("\tfloat:left;\r\n");
      out.write(" \tbackground-color:#ffa12c; width:auto; height:auto; \r\n");
      out.write(" } \r\n");
      out.write("\r\n");
      out.write(".img { \r\n");
      out.write("\tborder : 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tbackground-size: 100% 100%;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(".img:hover {\r\n");
      out.write("\r\n");
      out.write("\topacity:0.6;\r\n");
      out.write("\t\r\n");
      out.write("\tfilter:alpha(opacity=60); /* For IE8 and earlier */\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write(" \t position: relative;\r\n");
      out.write("     top:50%;\r\n");
      out.write("     left:50%;\r\n");
      out.write(" \t transform: translate(-50%, -50%);                                                       \r\n");
      out.write("/*      font-size:5rem; */\r\n");
      out.write("     color: white;\r\n");
      out.write("/*      z-index: 2; */\r\n");
      out.write("     text-align: center;\r\n");
      out.write("     display:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("<!-- \t<div id=\"aside\"> -->\r\n");
      out.write("<!-- \t\t좌측 메뉴 -->\r\n");
      out.write("<!-- \t</div> -->\r\n");
      out.write("\t<div id=\"category\">\r\n");
      out.write("\t\t<table width=\"100%\">\r\n");
      out.write("\t\t  <tbody><tr>\r\n");
      out.write("\t\t    <td height=\"585\" bgcolor=\"#f5eedb\"><table width=\"1000\" align=\"center\">\r\n");
      out.write("\t\t    \t<tbody><tr>\r\n");
      out.write("\t\t\t        <td>&nbsp;</td>\r\n");
      out.write("\t\t\t        <td width=\"195\" height=\"195\" style=\"vertical-align: middle;\">\r\n");
      out.write("\t\t\t        <div id=\"cafe\" class=\"img\" style=\"background-image: url(/img/mainPic/coffee2.jpg);\" onclick=\"location.href='/toplist.do?type=카페'\">\r\n");
      out.write("\t\t\t        <h1 id=\"cafeTitle\">카페</h1>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t        </td>\r\n");
      out.write("\t\t\t        <td height=\"195\" width=\"390\" colspan=\"2\">\r\n");
      out.write("\t\t\t        <div id=\"krFood\" class=\"img\" style=\"background-image: url(/img/mainPic/KrFood.png);\" onclick=\"location.href='/toplist.do?type=한식'\">\r\n");
      out.write("\t\t\t\t\t<h1 id=\"krFoodTitle\">한식</h1>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t        </td>\r\n");
      out.write("\t\t\t        <td>&nbsp;</td>\r\n");
      out.write("\t\t      \t</tr>\r\n");
      out.write("\t\t      \t<tr>\r\n");
      out.write("\t\t\t        <td>&nbsp;</td>\r\n");
      out.write("\t\t\t        <td width=\"195\" height=\"195\">\r\n");
      out.write("\t\t\t        <div id=\"jpFood\" class=\"img\" style=\"background-image: url(/img/mainPic/susi.jpg);\" onclick=\"location.href='/toplist.do?type=일식'\">\r\n");
      out.write("\t\t\t        <h1 id=\"jpFoodTitle\">일식</h1>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t        </td>\r\n");
      out.write("\t\t\t        <td width=\"195\" height=\"195\">\r\n");
      out.write("\t\t\t        <div id=\"drink\" class=\"img\" style=\"background-image: url(/img/mainPic/drink.jpg)\" onclick=\"location.href='/toplist.do?type=술집'\">\r\n");
      out.write("\t\t\t        <h1 id=\"drinkTitle\">술집</h1>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t        </td>\r\n");
      out.write("\t\t\t        <td width=\"195\" height=\"195\">\r\n");
      out.write("\t\t\t        <div id=\"wsFood\" class=\"img\" style=\"background-image: url(/img/mainPic/meat.jpg);\" onclick=\"location.href='/toplist.do?type=양식'\">\r\n");
      out.write("\t\t\t        <h1 id=\"wsFoodTitle\">양식 </h1>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t        </td>\r\n");
      out.write("\t\t\t        <td>&nbsp;</td>\r\n");
      out.write("\t\t      \t</tr>\r\n");
      out.write("\t\t     \t<tr>\r\n");
      out.write("\t\t\t        <td>&nbsp;</td>\r\n");
      out.write("\t\t\t        <td height=\"195\" width=\"390\" colspan=\"2\">\r\n");
      out.write("\t\t\t        <div id=\"chFood\" class=\"img\" style=\"background-image: url(/img/mainPic/china2.jpg);\" onclick=\"location.href='/toplist.do?type=중식'\">\r\n");
      out.write("\t\t\t        <h1 id=\"chFoodTitle\">중식</h1>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t        </td>\r\n");
      out.write("\t\t\t        <td width=\"195\" height=\"195\">\r\n");
      out.write("\t\t\t        <div id=\"snack\" class=\"img\" style=\"background-image: url(/img/mainPic/snack.jpg);\" onclick=\"location.href='/toplist.do?type=분식'\">\r\n");
      out.write("\t\t\t        <h1 id=\"snackTitle\">분식 </h1>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t        </td>\r\n");
      out.write("\t\t\t        <td>&nbsp;</td>\r\n");
      out.write("\t\t      \t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table></td>\r\n");
      out.write("\t\t  </tr></tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
