/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-04-24 06:43:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".footer{\r\n");
      out.write("\tbackground-color: rgb(89, 89, 89);\r\n");
      out.write("}\r\n");
      out.write("ul{\r\n");
      out.write("\tmargin-left:auto;\r\n");
      out.write("\tmargin-right:auto;\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: gray;\r\n");
      out.write("}\r\n");
      out.write("footer.footer {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    background-color: #3e3e3e;\r\n");
      out.write("}\r\n");
      out.write("article, aside, canvas, details, figcaption, figure, footer, header, nav, menu, nav, section, main {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("* {\r\n");
      out.write("    -webkit-tap-highlight-color: transparent;\r\n");
      out.write("}\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("/* user agent stylesheet */\r\n");
      out.write("/* article, aside, footer, header, hgroup, main, nav, section { */\r\n");
      out.write("/*     display: block; */\r\n");
      out.write("/* } */\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  <div class=\"inner\">\r\n");
      out.write("    <div class=\"mp_logo\">\r\n");
      out.write("      <a href=\"/00_Main.jsp\" class=\"btn-mp\">푸드뷰</a>\r\n");
      out.write("<!--       <p class=\"subtitle\">회사 소개말</p> -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"links-external\">\r\n");
      out.write("    \r\n");
      out.write("<!--       <ul class=\"list-links\"> -->\r\n");
      out.write("<!--           <li> -->\r\n");
      out.write("<!--             <a href=\"#\"> -->\r\n");
      out.write("<!--              \t회사소개 -->\r\n");
      out.write("<!--             </a> -->\r\n");
      out.write("<!--           </li> -->\r\n");
      out.write("<!--       </ul> -->\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"list-links\">\r\n");
      out.write("<!--             <li> -->\r\n");
      out.write("<!--               <a href=\"#\" target=\"_blank\"> -->\r\n");
      out.write("<!--                \t 공지사항 -->\r\n");
      out.write("<!--               </a> -->\r\n");
      out.write("<!--             </li> -->\r\n");
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("              <a class=\"\" href=\"/information/contract.jsp\" onclick=\"common_ga('PG_FOOTER', 'CLICK_TERMS', 'contract')\" target=\"_blank\">\r\n");
      out.write("               \t 이용약관\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a class=\"\" href=\"/information/contract_non_signup.jsp\" target=\"_blank\">\r\n");
      out.write("               \t 비회원 이용자 이용정책\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a class=\"bold\" href=\"/information/privacy.jsp\" target=\"_blank\">\r\n");
      out.write("                \t개인정보처리방침\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a class=\"\" href=\"/information/community_guide.jsp\" target=\"_blank\">\r\n");
      out.write("                \t커뮤니티 가이드라인\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("<!--             <li> -->\r\n");
      out.write("<!--               <a href=\"/01_faqWrite.jsp\"> -->\r\n");
      out.write("<!--                \t 문의하기 -->\r\n");
      out.write("<!--               </a> -->\r\n");
      out.write("<!--             </li> -->\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"language-copyrights\">\r\n");
      out.write("      <p>\r\n");
      out.write("        <p>\r\n");
      out.write("          ㈜ 푸드뷰  | 사업자 등록번호: 000-00-00000 |\r\n");
      out.write("          서울특별시 강남구 역삼동 85길 22, 4층<br>\r\n");
      out.write("          <span class=\"copyrights\">© 2018 FoodView Co., Ltd. All rights reserved.</span>\r\n");
      out.write("        </p>\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
