/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-04-24 06:43:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>푸드뷰</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tvar loginCheck = false;\r\n");
      out.write("\tjQuery.fn.extend({\r\n");
      out.write("\t    live: function (event, callback) {\r\n");
      out.write("\t       if (this.selector) {\r\n");
      out.write("\t            jQuery(document).on(event, this.selector, callback);\r\n");
      out.write("\t        }\r\n");
      out.write("\t    }\r\n");
      out.write("\t});\r\n");
      out.write("\t//로그인 팝업\r\n");
      out.write("\t$('a.login-window').click(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar loginBox = $(this).attr('href');\r\n");
      out.write("\r\n");
      out.write("\t\tvar popMargTop = ($(loginBox).height() + 24) / 2; \r\n");
      out.write("\t\tvar popMargLeft = ($(loginBox).width() + 24) / 2; \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(loginBox).css({ \r\n");
      out.write("\t\t\t'margin-top' : -popMargTop,\r\n");
      out.write("\t\t\t'margin-left' : -popMargLeft\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$div = $('<div id=\"mask\"></div>');\r\n");
      out.write("\r\n");
      out.write("\t\t$('body').append('<div id=\"mask\"></div>');\r\n");
      out.write("\t\t$(loginBox).fadeIn(300);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('a.close, #mask').live('click', function() { \r\n");
      out.write("\t  $('#mask , .login-popup').fadeOut(300 , function() {\r\n");
      out.write("\t\t$('#mask').remove();  \r\n");
      out.write("\t}); \r\n");
      out.write("\treturn false;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#login-btn\").click(function(){\r\n");
      out.write("\t\tif($(\"#username\").val()==null||$(\"#username\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\t$(\"#username\").focus();\r\n");
      out.write("\t\t}else if($(\"#password\").val()==null||$(\"#password\").val==\"\"){\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\t$(\"#password\").focus();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:'POST',\r\n");
      out.write("\t\t\t\turl:'/LoginCheckServlet.do',\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\"id\":$(\"#username\").val(),\r\n");
      out.write("\t\t\t\t\t\"pw\":$(\"#password\").val()\r\n");
      out.write("\t\t\t\t}, success:function(data){\r\n");
      out.write("\t\t\t\t\tif($.trim(data)==\"true\"){\r\n");
      out.write("\t\t\t\t\t\t$('.login-popup').fadeOut(300 , function() {\r\n");
      out.write("\t\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}else if($.trim(data)==\"false\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"아이디와 비밀번호를 확인해주세요\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("// \t\t\t\t\talert(\"ajax 연결\");\r\n");
      out.write("\t\t\t\t}, error:function(request, error){\r\n");
      out.write("\t\t\t\t\tconsole.log(request.responseText);\r\n");
      out.write("\t\t\t\t\tconsole.log(error.printStackTrace);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#Manager-login-btn\").click(function(){\r\n");
      out.write("\t\tif ( $(\"#admin_name\").val() == null || $(\"#admin_name\").val() == \"\" ) {\r\n");
      out.write("\t\t\talert(\"관리자 아이디를 입력하세요.\")\r\n");
      out.write("\t\t\t$(\"#admin_name\").focus();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else if ( $(\"#admin_password\").val() == null || $(\"#admin_password\").val() == \"\" ) {\r\n");
      out.write("\t\t\talert(\"관리자 패스워드를 입력하세요.\")\r\n");
      out.write("\t\t\t$(\"#admin_password\").focus();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype : \"POST\"\r\n");
      out.write("\t\t\t\t,\turl : \"/ManagerLoginCheckServlet.do\"\r\n");
      out.write("\t\t\t\t,\tdataType: \"json\"\r\n");
      out.write("\t\t\t\t,\tdata : { \"id\" : $(\"#admin_name\").val()\r\n");
      out.write("\t\t\t\t\t,\t\t \"pw\" : $(\"#admin_password\").val()}\r\n");
      out.write("\t\t\t\t,\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif ( $.trim(data) == \"true\" ) {\r\n");
      out.write("\t\t\t\t\t\t$('.login-popup').fadeOut(300, function() {\r\n");
      out.write("\t\t\t\t\t\t\tlocation.replace('/manager/postlist.do');\t\r\n");
      out.write("\t\t\t\t\t\t});\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t} else if ( $.trim(data) == \"false\" ) {\r\n");
      out.write("\t\t\t\t\t\talert(\"아이디와 비밀번호를 확인해주세요!\");\r\n");
      out.write("\t\t\t\t\t}\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}, error : function (request, error) {\r\n");
      out.write("\t\t\t\t\tconsole.log(request.responseText);\r\n");
      out.write("\t\t\t\t\tconsole.log(error.printStackTrace);\r\n");
      out.write("\t\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t\t})\t\t\t\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$('#join-btn').click(function(){\r\n");
      out.write("\t\tlocation.href=\"/member/memberjoin.do\";\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#gnb {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 메뉴 */\r\n");
      out.write("ul {\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul li {\r\n");
      out.write("/* \tfloat: right; */\r\n");
      out.write("\tmargin: 0px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li ul {\r\n");
      out.write("\tbackground: rgb(109, 109, 109);\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tz-index: 200;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menu:hover ul {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 검색창 */\r\n");
      out.write("#search {\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("\tmargin-right: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search_text {\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-sign a {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\ttext-shadow: 0 1px 2px #161616;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mask {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: #000;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tz-index: 10;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\topacity: 0.8;\r\n");
      out.write("\tz-index: 999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-popup {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: #333;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tborder: 2px solid #ddd;\r\n");
      out.write(" \tfloat: left; \r\n");
      out.write("\tfont-size: 1.2em;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\tz-index: 99999;\r\n");
      out.write("\tbox-shadow: 0px 0px 20px #999;\r\n");
      out.write("\t-moz-box-shadow: 0px 0px 20px #999; /* Firefox */\r\n");
      out.write("\t-webkit-box-shadow: 0px 0px 20px #999; /* Safari, Chrome */\r\n");
      out.write("\tborder-radius: 3px 3px 3px 3px;\r\n");
      out.write("\t-moz-border-radius: 3px; /* Firefox */\r\n");
      out.write("\t-webkit-border-radius: 3px; /* Safari, Chrome */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.btn_close {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin: -28px -28px 0 0;\r\n");
      out.write("\tborder: 0; /* 익스플러에서 닫기 버튼 테두리 나타나는 문제 해결 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("fieldset {\r\n");
      out.write("\tborder: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.signin .textbox label {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding-bottom: 7px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.signin .textbox span {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.signin p, form.signin span {\r\n");
      out.write("\tcolor: #999;\r\n");
      out.write("\tfont-size: 10px;\r\n");
      out.write("\tline-height: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.signin .textbox input {\r\n");
      out.write("\tbackground: #666666;\r\n");
      out.write("\tborder-bottom: 1px solid #333;\r\n");
      out.write("\tborder-left: 1px solid #000;\r\n");
      out.write("\tborder-right: 1px solid #333;\r\n");
      out.write("\tborder-top: 1px solid #000;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tborder-radius: 3px 3px 3px 3px;\r\n");
      out.write("\t-moz-border-radius: 3px;\r\n");
      out.write("\t-webkit-border-radius: 3px;\r\n");
      out.write("\tfont: 13px Arial, Helvetica, sans-serif;\r\n");
      out.write("\tpadding: 6px 6px 4px;\r\n");
      out.write("\twidth: 180px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.signin input:-moz-placeholder {\r\n");
      out.write("\tcolor: #bbb;\r\n");
      out.write("\ttext-shadow: 0 0 2px #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.signin input::-webkit-input-placeholder {\r\n");
      out.write("\tcolor: #bbb;\r\n");
      out.write("\ttext-shadow: 0 0 2px #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("\tbackground: -moz-linear-gradient(center top, #f3f3f3, #dddddd);\r\n");
      out.write("\tbackground: -webkit-gradient(linear, left top, left bottom, from(#f3f3f3),\r\n");
      out.write("\t\tto(#dddddd));\r\n");
      out.write("\tbackground: -o-linear-gradient(top, #f3f3f3, #dddddd);\r\n");
      out.write("\tfilter: progid:DXImageTransform.Microsoft.gradient(startColorStr='#f3f3f3',\r\n");
      out.write("\t\tEndColorStr='#dddddd');\r\n");
      out.write("\tborder-color: #000;\r\n");
      out.write("\tborder-width: 1px;\r\n");
      out.write("\tborder-radius: 4px 4px 4px 4px;\r\n");
      out.write("\t-moz-border-radius: 4px;\r\n");
      out.write("\t-webkit-border-radius: 4px;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: 6px 6px 4px;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\tfont: 12px;\r\n");
      out.write("\twidth: 214px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .button:hover { background:#ddd; } */\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- wrapper 시작 -->\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<!-- header 시작 -->\r\n");
      out.write("\t\t<div id=\"header\" style=\"height: 200px; position: relative; z-index: 100; background-color: rgb(252, 250, 225);\">\r\n");
      out.write("\t\t\t<!-- 로고 -->\r\n");
      out.write("\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t<a href=\"/FoodView.com\"><img src=\"/img/foodview.png\"></a>\r\n");
      out.write("<!-- \t\t\t\t\t<h1 style=\"color: rgb(255, 119, 41);\">푸드뷰</h1></a> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 메뉴 -->\t\t\t\r\n");
      out.write("\t\t\t<div id=\"gnb\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"menu3\"><a href=\"#login-box\" class=\"login-window\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								String id = "";
								id = (String) session.getAttribute("id");
								String pw = "";
								pw = (String) session.getAttribute("pw");

								if (id == null || "".equals(id) || pw == null || "".equals(pw)) {
							
      out.write(" 로그인 ");

								} else if (id == "admin" || id.equals("admin")) {
							
      out.write(" <script>location.href=\"/manager/10_main.jsp\";</script> ");

 	} else {
 
      out.write(" 내 정보 ");

 	}
 
      out.write("\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"menu3\"><a href=\"#Manager-login-box\" class=\"login-window\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								String Admin_id = "";
								Admin_id = (String) session.getAttribute("id");
								String Admin_pw = "";
								Admin_pw = (String) session.getAttribute("pw");

								if (id == null || "".equals(id) || pw == null || "".equals(pw)) {
							
      out.write(" 관리자 로그인 ");

								} else if (Admin_id == "admin" || Admin_id.equals("admin")) {
							
      out.write(" <script>location.href=\"/manager/10_main.jsp\";</script> ");

 	} else {
 
      out.write(" 관리자 페이지로 ");

 	}
 
      out.write("\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 로그인 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"login-box\" class=\"login-popup\"\r\n");
      out.write("\t\t\t\tstyle=\"display: none; margin-top: -94px; margin-left: -135.5px;\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"close\"><img src=\"/img/close_pop.png\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn_close\" title=\"Close Window\" alt=\"Close\"></a>\r\n");
      out.write("\t\t\t\t");

					id = (String) session.getAttribute("id");
					pw = (String) session.getAttribute("pw");

					if (id == null || "".equals(id) || pw == null || "".equals(pw)) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<form method=\"post\" class=\"signin\" action=\"/LoginCheckServlet.do\" style=\"width:220px; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t<fieldset class=\"textbox\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"username\"><span>ID</span> <input id=\"username\" name=\"username\" value=\"\" type=\"text\" autocomplete=\"on\" placeholder=\"Username\"></label> \r\n");
      out.write("\t\t\t\t\t\t<label class=\"password\"><span>Password</span> <input id=\"password\" name=\"password\" value=\"\" type=\"password\" placeholder=\"Password\"></label> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" id=\"login-btn\" value=\"로그인\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" id=\"join-btn\" value=\"회원가입\">\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t<label class=\"findInfo\"><p><a href=\"/userhelp.do\">아이디/비밀번호 찾기</a></p></label>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");

          	} else {
          
      out.write("\r\n");
      out.write("\t\t\t\t<label class=\"userId\"> <span>");
      out.print( session.getAttribute("id"));
      out.write("</span><br>\r\n");
      out.write("\t\t\t\t</label> <label class=\"mypage\"> <span><a href=\"/mypage.do\">마이페이지</a></span><br>\r\n");
      out.write("\t\t\t\t</label> <label class=\"logout\"> <span><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/main/logout.jsp\">로그아웃</a></span>\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t");

          	};
       	
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"Manager-login-box\" class=\"login-popup\"\r\n");
      out.write("\t\t\t\tstyle=\"display: none; margin-top: -94px; margin-left: -135.5px;\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"close\"><img src=\"img/close_pop.png\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn_close\" title=\"Close Window\" alt=\"Close\"></a>\r\n");
      out.write("\t\t\t\t");

					Admin_id = (String) session.getAttribute("id");
					Admin_pw = (String) session.getAttribute("pw");

					if (Admin_id == null || "".equals(Admin_id) || Admin_pw == null || "".equals(Admin_pw)) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<form method=\"post\" class=\"signin\" action=\"/ManagerLoginCheckServlet.do\">\r\n");
      out.write("\t\t\t\t\t<fieldset class=\"textbox\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"admin_name\"> <span>ID</span> \r\n");
      out.write("\t\t\t\t\t\t<input id=\"admin_name\" name=\"admin_name\" value=\"\" type=\"text\" autocomplete=\"on\" placeholder=\"Admin\">\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t<label class=\"password\"> <span>Password</span> \r\n");
      out.write("\t\t\t\t\t\t<input id=\"admin_password\" name=\"admin_password\" value=\"\" type=\"password\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" id=\"Manager-login-btn\" value=\"관리자 로그인\"> \r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");

          	} else {
          
      out.write("\r\n");
      out.write("\t\t\t\t<label class=\"userId\"> <span>");
      out.print( session.getAttribute("id"));
      out.write("</span></label><br>\r\n");
      out.write("\t\t\t\t<label class=\"mypage\"> <span><a href=\"/mypage.do\">마이페이지</a></span></label><br>\r\n");
      out.write("\t\t\t\t<label class=\"logout\"> <span><a href=\"/main/logout.jsp\">로그아웃</a></span>\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t");

          	};
       	
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 검색창 -->\r\n");
      out.write("\t\t\t<form action=\"/search.do\" >\r\n");
      out.write("\t\t\t<div id=\"search\">\r\n");
      out.write("\t\t\t\t<label class=\"search\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\"  id=\"searchShop\" name=\"searchShop\" value=\"search\">\r\n");
      out.write("\t\t\t\t<select name=\"searchName\" size=\"1\" style=\"height: 40px;\">\r\n");
      out.write("\t\t\t\t\t<option value=\"shopSearch\">음식점명</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"foodSearch\">음식명</option>\r\n");
      out.write("          \t \t</select>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"search_text\" name=\"searchValue\" placeholder=\"음식점 리뷰 검색\" />\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" style=\"height: 45px;\">\r\n");
      out.write("\t\t\t\t\t검색\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<!-- header 끝 -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- wrapper 끝 -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
