/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-05-11 04:06:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberJoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/mypage.css\" />\r\n");
      out.write("<style> \r\n");
      out.write("\r\n");
      out.write("div#contents label {\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   width: 120px;\r\n");
      out.write("   margin-left: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#contents div {\r\n");
      out.write("\tmargin: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tvar idCheck = false;\r\n");
      out.write("\tvar pwCheck = false;\r\n");
      out.write("\t\r\n");
      out.write("\t $(\"#uIdNum\").blur(function(){\r\n");
      out.write("    \tvar num = $(\"#uIdNum\").val();\r\n");
      out.write("    \tidNo_blur(num);\r\n");
      out.write("\t });\r\n");
      out.write("\r\n");
      out.write("    $(\"#uIdNum\").click(function(){\r\n");
      out.write("    \tvar num = $(\"#uIdNum\").val();\r\n");
      out.write("    \tidNo_focus(num);\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("\tfunction idNo_focus(num) {\r\n");
      out.write("\t\tnum = num.replace(/[^0-9]/g, '');\r\n");
      out.write("\t\t$(\"#uIdNum\").val(num);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction idNo_blur(num) {\r\n");
      out.write("\t\tnum = num.replace(/[^0-9]/g, '');\r\n");
      out.write("\t\tvar tmp = '';\r\n");
      out.write("\t\ttmp += num.substr(0, 6);\r\n");
      out.write("\t\ttmp += '-';\r\n");
      out.write("\t\ttmp += num.substr(6, 13);\r\n");
      out.write("\t\t$(\"#uIdNum\").val(tmp);\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#pno\").blur(function(){\r\n");
      out.write("    \tvar num = $(\"#pno\").val();\r\n");
      out.write("    \tpno_blur(num)\r\n");
      out.write("\t });\r\n");
      out.write("\r\n");
      out.write("    $(\"#pno\").click(function(){\r\n");
      out.write("    \tvar num = $(\"#pno\").val();\r\n");
      out.write("    \tpno_focus(num);\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("\tfunction pno_focus(num) {\r\n");
      out.write("\t\tnum = num.replace(/[^0-9]/g, '');\r\n");
      out.write("\t\t$(\"#pno\").val(num);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction pno_blur(num) {\r\n");
      out.write("\t\tnum = num.replace(/[^0-9]/g, '');\r\n");
      out.write("\t\tvar tmp = '';\r\n");
      out.write("\t\ttmp += num.substr(0, 3);\r\n");
      out.write("\t\ttmp += '-';\r\n");
      out.write("\t\ttmp += num.substr(3, 4);\r\n");
      out.write("\t\ttmp += '-';\r\n");
      out.write("\t\ttmp += num.substr(7, 13);\r\n");
      out.write("\t\t$(\"#pno\").val(tmp);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(\"#idCheckbtn\").click(function(){\r\n");
      out.write("\t\tif($(\"#uId\").val()==null||$(\"#uId\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:'POST',\r\n");
      out.write("\t\t\t\turl:'/idCheck.do',\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\"id\":$(\"#uId\").val()\r\n");
      out.write("\t\t\t\t}, success:function(data){\r\n");
      out.write("\t\t\t\t\tif($.trim(data)==\"true\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"사용 가능한 아이디입니다!\");\r\n");
      out.write("\t\t\t\t\t\tidCheck = true;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(\"사용할 수 없는 아이디입니다!\");\r\n");
      out.write("\t\t\t\t\t\tidCheck = false;\r\n");
      out.write("\t\t\t\t\t\t$(\"#uId\").focus();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}, error:function(request, error){\r\n");
      out.write("\t\t\t\t\tconsole.log(request.responseText);\r\n");
      out.write("\t\t\t\t\tconsole.log(error.printStackTrace);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#pwCheckBtn\").click(function(){\r\n");
      out.write("\t\tvar pw = $(\"#pw\").val();\r\n");
      out.write("\t\tif($(\"#pw\").val()==null||$(\"#pw\").val()==\"\"||$(\"#pwCheck\").val()==null||$(\"#pwCheck\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else if(pw.length<12){\r\n");
      out.write("\t\t\talert(\"비밀번호는 13자 이상 작성해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"#pw\").val()!=$(\"#pwCheck\").val()){\r\n");
      out.write("\t\t\talert(\"입력된 비밀번호가 다릅니다!\");\r\n");
      out.write("\t\t\t$(\"#pwCheckTxt\").css(\"display\", \"none\")\r\n");
      out.write("\t\t\tpwCheck = false;\r\n");
      out.write("\t\t\t$(\"#pwCheck\").focus();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#pwCheckTxt\").css(\"display\", \"inline-block\")\r\n");
      out.write("\t\t\tpwCheck = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#submitBtn\").click(function(){\r\n");
      out.write("\t\t\tif($(\"#uName\").val()==\"\"||$(\"#uName\").val()==null){\r\n");
      out.write("\t\t\t\talert(\"이름을 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#uName\").focus();\r\n");
      out.write("\t\t\t}else if($(\"#uIdNum\").val()==\"\"||$(\"#uIdNum\").val()==null){\r\n");
      out.write("\t\t\t\talert(\"주민번호를 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#uIdNum\").focus();\r\n");
      out.write("\t\t\t}else if($(\"#uId\").val()==\"\"||$(\"#uId\").val()==null){\r\n");
      out.write("\t\t\t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#uId\").focus();\r\n");
      out.write("\t\t\t}else if($(\"#pw\").val()==\"\"||$(\"#pw\").val()==null){\r\n");
      out.write("\t\t\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#pw\").focus();\r\n");
      out.write("\t\t\t}else if($(\"#pno\").val()==\"\"||$(\"#pno\").val()==null){\r\n");
      out.write("\t\t\t\talert(\"휴대폰 번호를 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#pno\").focus();\r\n");
      out.write("\t\t\t}else if($(\"#addr\").val()==\"\"||$(\"#addr\").val==null){\r\n");
      out.write("\t\t\t\talert(\"주소를 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#addr\").focus();\r\n");
      out.write("\t\t\t}else if($(\"#email\").val()==\"\"||$(\"#email\").val()==null){\r\n");
      out.write("\t\t\t\talert(\"이메일을 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#email\").focus();\r\n");
      out.write("\t\t\t}else if($(\"#nick\").val()==\"\"||$(\"#nick\").val()==null){\r\n");
      out.write("\t\t\t\talert(\"닉네임을 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#nick\").focus();\r\n");
      out.write("\t\t\t}else if($(\":radio[name='gender']:checked\").length<1){\r\n");
      out.write("\t\t\t\talert(\"성별을 선택하세요\");\r\n");
      out.write("\t\t\t\t$(\"#gender\").focus();\r\n");
      out.write("// \t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif(pwCheck&&idCheck){\r\n");
      out.write("\t\t\t\tconsole.log(\"OK\");\r\n");
      out.write("\t\t\t\t$(\"#memberJoin\").submit();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tif(!pwCheck){\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호를 확인해주세요\");\r\n");
      out.write("\t\t\t\t\t$(\"#pwCheck\").focus();\r\n");
      out.write("\t\t\t\t}else if(!idCheck){\r\n");
      out.write("\t\t\t\t\talert(\"아이디 중복을 확인해주세요\");\r\n");
      out.write("\t\t\t\t\t$(\"#uId\").focus();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/main/top.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"contents\">\r\n");
      out.write("\t<h1>회원가입</h1>\r\n");
      out.write("\t\t<div id=\"form\" class=\"form-inline\">\r\n");
      out.write("\t\t<form action=\"/MemberJoin.do\" method=\"post\" id=\"memberJoin\">\r\n");
      out.write("\t\t\t<label>이름 : </label><input type=\"text\" id=\"uName\" name=\"uName\" class=\"form-control\" size=\"30\"/><br>\r\n");
      out.write("\t\t\t<label>주민번호 : </label><input type=\"text\" id=\"uIdNum\" name=\"uIdNum\" class=\"form-control\" size=\"30\"/><br>\r\n");
      out.write("\t\t\t<label>아이디 : </label><input type=\"text\" id=\"uId\" name=\"uId\" class=\"form-control\" size=\"30\" maxlength=\"12\"/><input type=\"button\" id=\"idCheckbtn\" value=\"중복 확인\"/><br>\r\n");
      out.write("\t\t\t<label>비밀번호 : </label><input type=\"password\" id=\"pw\" name=\"pw\" class=\"form-control\" size=\"30\" maxlength=\"30\"/><br>\r\n");
      out.write("\t\t\t<label>비밀번호 확인 : </label><input type=\"password\" id=\"pwCheck\" class=\"form-control\" size=\"30\" maxlength=\"30\"/><input type=\"button\" id=\"pwCheckBtn\" value=\"비밀번호 확인\"><br>\r\n");
      out.write("\t\t\t<label id = \"pwCheckTxt\" style=\"display:none;\">비밀번호 확인 완료</label><br>\r\n");
      out.write("\t\t\t<label>휴대폰 번호 : </label><input type=\"text\" id=\"pno\" name=\"pno\" class=\"form-control\" size=\"30\"/><br>\r\n");
      out.write("\t\t\t<label>주소 : </label><input type=\"text\" id=\"addr\" name=\"addr\" class=\"form-control\" size=\"30\"/><br>\r\n");
      out.write("\t\t\t<label>이메일 : </label><input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\" size=\"30\"/><br>\r\n");
      out.write("\t\t\t<label>닉네임 : </label><input type=\"text\" id=\"nick\" name=\"nick\" class=\"form-control\" size=\"30\"/><br>\r\n");
      out.write("\t\t\t<label>성별 : </label>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"gender\" value=\"M\"/>남\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"gender\" value=\"F\"/>여\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"submitBtn\" value=\"완료\">\r\n");
      out.write("\t\t\t<input type=\"reset\" id=\"cancelBtn\" value=\"취소\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/main/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
